version: '3.8'
services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    environment: 
      # Database Configuration
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DB_SYNCHRONIZE=true
      # App variables
      - CLIENT_URL=http://localhost:3000
      # Seeder
      - SEEDER_SHOULD_SEED=true
    ports: 
      - 3001:3001
    volumes: 
      - /app/node_modules
      - .:/app

volumes: 
  postgres: